### ISSUE TITLE
Repo name

### ISSUE THREAD

**Issue by xji3** [Ldo3/linhdo154.github.io#1]
Hi Linh,
For the github site to work, you might want to change the repo name to `Ldo3.github.io`.
Xiang

**Comment by Ldo3** [comment]
> Hi Linh,
> For the github site to work, you might want to change the repo name to `Ldo3.github.io`.
> Xiang
Dear Prof. Ji,
Thank you so much for your instructions. I am trying to create my personal webpage using Github. I am surprised that you noticed my editing here. I finally found online instructions on following and editing the webpage locally before publishing it. I will change the name of the repo to Ldo3. Thank you so much for your help.
Yours sincerely,
Linh Do
